DECLARE @i INT = -1
DECLARE @partition INT
DECLARE @sql VARCHAR(MAX)

WHILE @i >= -7
BEGIN
	SET @partition = (SELECT HISTORY.$PARTITION.pfHistoryDay(DATEADD(day, @i, CAST(GETDATE() AS DATE))))
	SET @sql = 'ALTER INDEX idx1 ON HISTORY.dbo.T_SERVICE_LVL_LS_WHS_switch_test REBUILD PARTITION = ' + CAST(@partition AS VARCHAR(10)) + ' WITH (DATA_COMPRESSION = PAGE)'
	TRUNCATE TABLE HISTORY.dbo.T_SERVICE_LVL_LS_WHS_switch
	ALTER TABLE HISTORY.dbo.T_SERVICE_LVL_LS_WHS_switch_test SWITCH PARTITION @partition TO HISTORY.dbo.T_SERVICE_LVL_LS_WHS_switch PARTITION @partition
	TRUNCATE TABLE HISTORY.dbo.T_SERVICE_LVL_LS_WHS_switch
	EXEC (@sql)
	PRINT @sql
	SET @i = @i -1
END
